"""Utilities shared by the magic-state distillation demo notebooks."""

from .circuits import (
    DecoderKernelBundle,
    NaiveKernelBundle,
    build_decoder_kernel_bundle,
    build_naive_kernel_bundle,
    build_paper_decoder_kernel_bundle,
    build_task,
    build_task_map,
    make_noisy_steane7_initializer,
)
from .core import (
    DEFAULT_BASIS_LABELS,
    DEFAULT_IDEAL_FACTORY_ACCEPTANCE,
    DEFAULT_TARGET_BLOCH,
    BasisDataset,
    bits_to_key,
    fidelity_from_counts,
    infer_distilled_sign_vector,
    infer_factory_target,
    key_to_bits,
    logical_expectation,
    magic_state_fidelity_point_from_counts,
    naive_distilled_summary,
    naive_injected_summary,
    pack_boolean_array,
    run_task,
    split_factory_bits,
)
from .decoders import (
    DecoderAdapter,
    build_mld_decoders,
    build_mle_decoders,
    build_shared_mld_postselection_scores,
    compute_dem_data,
    evaluate_curve,
    evaluate_mld_curve,
    injected_baseline,
    make_shape_only_dem,
    matrix_to_dem,
)
from .noise import (
    DistillationSimNoiseConfig,
    build_distillation_sim_noise_model,
)

__all__ = [
    "BasisDataset",
    "DEFAULT_BASIS_LABELS",
    "DEFAULT_IDEAL_FACTORY_ACCEPTANCE",
    "DEFAULT_TARGET_BLOCH",
    "DecoderAdapter",
    "DecoderKernelBundle",
    "DistillationSimNoiseConfig",
    "NaiveKernelBundle",
    "bits_to_key",
    "build_decoder_kernel_bundle",
    "build_mld_decoders",
    "build_mle_decoders",
    "build_naive_kernel_bundle",
    "build_paper_decoder_kernel_bundle",
    "build_distillation_sim_noise_model",
    "build_shared_mld_postselection_scores",
    "build_task",
    "build_task_map",
    "compute_dem_data",
    "evaluate_curve",
    "evaluate_mld_curve",
    "fidelity_from_counts",
    "infer_distilled_sign_vector",
    "infer_factory_target",
    "injected_baseline",
    "key_to_bits",
    "logical_expectation",
    "magic_state_fidelity_point_from_counts",
    "make_noisy_steane7_initializer",
    "make_shape_only_dem",
    "matrix_to_dem",
    "naive_distilled_summary",
    "naive_injected_summary",
    "pack_boolean_array",
    "run_task",
    "split_factory_bits",
]
