//! Behaviour net for `bloqade-lanes-search`.
//!
//! This suite detects *any* behaviour change in the crate, and is laid out so
//! that API churn has a single point of failure. It has three strictly
//! separated layers:
//!
//! - **`cases.rs`**: the case corpus, as plain data. No crate types.
//! - **`interface.rs`**: the only module that imports the crate. It turns a
//!   case into crate calls and the result into an [`spec::Outcome`]. Read its
//!   module doc before changing anything.
//! - **this file**: the runner. It checks each semantic case's hand-verified
//!   expectations, and compares every case's rendered outcome against the
//!   committed golden file.
//!
//! When a behaviour change is intended, regenerate the golden and review the
//! diff:
//!
//! ```text
//! BEHAVIOUR_BLESS=1 cargo test -p bloqade-lanes-search --test behaviour
//! ```
//!
//! The golden is recorded in a debug build, which is what `cargo test` and CI
//! use. Under `--release` the golden comparison is skipped, since a
//! `debug_assert!` can end a case that a release build would run through.

mod cases;
mod interface;
mod spec;

use std::path::PathBuf;
use std::sync::OnceLock;

use spec::{Expect, Outcome};

const GOLDEN: &str = "tests/fixtures/behaviour/golden.txt";
const BLESS_VAR: &str = "BEHAVIOUR_BLESS";

struct Ran {
    name: String,
    expect: Expect,
    outcome: Outcome,
}

/// Every case, run once and shared by the tests below.
fn outcomes() -> &'static [Ran] {
    static RUNS: OnceLock<Vec<Ran>> = OnceLock::new();
    RUNS.get_or_init(|| {
        cases::all()
            .into_iter()
            .map(|case| Ran {
                outcome: interface::run(&case.spec),
                name: case.name,
                expect: case.expect,
            })
            .collect()
    })
}

fn render_all() -> String {
    let mut out = String::from(
        "# Behaviour-net golden for bloqade-lanes-search.\n\
         # Generated by tests/behaviour; do not edit by hand. Regenerate with\n\
         # BEHAVIOUR_BLESS=1 cargo test -p bloqade-lanes-search --test behaviour\n\
         #\n\
         # One block per case, in corpus order, starting `== <case name>`. A block\n\
         # is either one `error: <message>` or `panicked: <first line>` line, or:\n\
         #   status: <solved|unsolvable|budget_exceeded> | layers: <AOD shots>\n\
         #     | lanes: <lanes over all shots> | cost: <plan cost> | expanded: <nodes>\n\
         #     | generated: <graph nodes> | deadlocks: <n> | proven: <bool>\n\
         #     | termination: <budget|exhausted|exhausted_proof|stopped>\n\
         #   final: <qubit>@<word>.<site> ...   (zone 0; other zones <zone>:<word>.<site>)\n\
         #   plan: <FNV-1a digest of the move sequence; cbf29ce484222325 = no moves>\n\
         #   partial: unresolved=<atoms off target> layers=<n> plan=<digest>\n\
         #     (a failed point-goal search only: the furthest configuration reached)\n\
         #   bound: cuts_g= cuts_h= cuts_inf= root_lb= incumbent=   (a real bound only)\n\
         #   attempts: chosen=<index|none> total=<nodes> [<index>:<status>/<nodes>, ...]\n\
         #     (placements that report candidate attempts only)\n",
    );
    for run in outcomes() {
        out.push_str(&format!("\n== {}\n{}", run.name, run.outcome.render()));
    }
    out
}

#[test]
fn case_names_are_unique() {
    let mut names: Vec<String> = cases::all().into_iter().map(|c| c.name).collect();
    let total = names.len();
    names.sort();
    names.dedup();
    assert_eq!(names.len(), total, "two cases share a name");
}

#[test]
fn semantic_expectations_hold() {
    let mut failures = Vec::new();
    for run in outcomes() {
        if run.expect.is_empty() {
            continue;
        }
        if let Some(problem) = check(&run.expect, &run.outcome) {
            failures.push(format!(
                "{}: {problem}\n  got: {}",
                run.name,
                run.outcome.render().trim_end()
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "semantic expectations failed:\n{}",
        failures.join("\n")
    );
}

fn check(expect: &Expect, outcome: &Outcome) -> Option<String> {
    match outcome {
        Outcome::Error(_) if expect.error => None,
        Outcome::Panicked(_) if expect.panic => None,
        _ if expect.error => Some("expected an error".into()),
        _ if expect.panic => Some("expected a panic".into()),
        Outcome::Error(msg) => Some(format!("unexpected error: {msg}")),
        Outcome::Panicked(msg) => Some(format!("unexpected panic: {msg}")),
        Outcome::Ran(run) => {
            if let Some(status) = expect.status
                && status != run.status
            {
                return Some(format!("expected status {status:?}"));
            }
            if let Some(layers) = expect.layers
                && layers != run.layers
            {
                return Some(format!("expected {layers} layers"));
            }
            if let Some(proven) = expect.proven
                && proven != run.proven
            {
                return Some(format!("expected proven = {proven}"));
            }
            None
        }
    }
}

#[test]
fn characterization_matches_golden() {
    if !cfg!(debug_assertions) {
        eprintln!("behaviour golden is recorded in a debug build; skipping under --release");
        return;
    }
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(GOLDEN);
    let actual = render_all();
    if std::env::var_os(BLESS_VAR).is_some() {
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, &actual).unwrap();
        eprintln!("wrote {}", path.display());
        return;
    }
    let expected = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| {
            panic!(
                "read {}: {e}; run with {BLESS_VAR}=1 to create it",
                path.display()
            )
        })
        .replace("\r\n", "\n");
    if expected != actual {
        let diff = similar::TextDiff::from_lines(&expected, &actual)
            .unified_diff()
            .context_radius(2)
            .header("golden", "actual")
            .to_string();
        panic!(
            "behaviour changed. If the change is intended, regenerate with \
             {BLESS_VAR}=1 and review the diff; otherwise it is a regression.\n{diff}"
        );
    }
}

/// The contract that makes this suite survive API churn: only
/// `interface.rs` may name the crate.
#[test]
fn only_the_interface_layer_imports_the_crate() {
    let dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/behaviour");
    let needles = [
        concat!("bloqade_lanes", "_search"),
        concat!("bloqade_lanes", "_bytecode_core"),
    ];
    for file in ["main.rs", "cases.rs", "spec.rs"] {
        let text = std::fs::read_to_string(dir.join(file)).unwrap();
        // Code only: comments may talk about the crate.
        let code = text.lines().filter(|l| !l.trim_start().starts_with("//"));
        for (line, needle) in code.flat_map(|l| needles.map(|n| (l, n))) {
            assert!(
                !line.contains(needle),
                "{file} names `{needle}`; only interface.rs may import the crate:\n  {line}"
            );
        }
    }
}
